ALTER TABLE "users" ADD COLUMN "tokenVersion" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "calendar_notes" ADD COLUMN "updatedBy" TEXT NOT NULL DEFAULT '';
ALTER TABLE "notices" ADD COLUMN "updatedBy" TEXT NOT NULL DEFAULT '';
