import RegistrationsChartOverlay from "./RegistrationsChartOverlay"
import RegistrationsDialogs from "./RegistrationsDialogs"

export default function RegistrationsShellOverlays(props: any) {
  const {
    chartOverlayOpen,
    setChartOverlayOpen,
    activeGanttGroup,
    registrationMap,
    resolveCourseDays,
    openWithdrawDialog,
    handleRestore,
    openTransferDialog,
    handleTransferCancel,
    openNoteDialog,
    showTransferChain,
    simulationDate,
    canManageTransfers,
    noteDialogOpen,
    closeNoteDialog,
    noteTarget,
    noteValue,
    setNoteValue,
    noteUpdatedAtLabel,
    noteError,
    noteSaving,
    handleNoteSave,
    withdrawDialogOpen,
    closeWithdrawDialog,
    withdrawTarget,
    withdrawDate,
    setWithdrawDate,
    withdrawPickerOpen,
    setWithdrawPickerOpen,
    withdrawError,
    withdrawSaving,
    handleWithdrawSave,
    transferDialogOpen,
    closeTransferDialog,
    transferTarget,
    transferDate,
    setTransferDate,
    transferPickerOpen,
    setTransferPickerOpen,
    transferCourseValue,
    setTransferCourseValue,
    transferWeeks,
    transferError,
    transferSaving,
    transferCourseGroups,
    transferCourseDays,
    transferExpectedEndDate,
    handleTransferSave,
    mergeError,
    setMergeError,
  } = props

  return (
    <>
      <RegistrationsChartOverlay
        open={chartOverlayOpen}
        onOpenChange={setChartOverlayOpen}
        activeGanttGroup={activeGanttGroup}
        registrationMap={registrationMap}
        resolveCourseDays={resolveCourseDays}
        openWithdrawDialog={openWithdrawDialog}
        handleRestore={handleRestore}
        openTransferDialog={openTransferDialog}
        handleTransferCancel={handleTransferCancel}
        openNoteDialog={openNoteDialog}
        showTransferChain={showTransferChain}
        simulationDate={simulationDate}
        canManageTransfers={canManageTransfers}
      />
      <RegistrationsDialogs
        noteDialogOpen={noteDialogOpen}
        closeNoteDialog={closeNoteDialog}
        noteTarget={noteTarget}
        noteValue={noteValue}
        setNoteValue={setNoteValue}
        noteUpdatedAtLabel={noteUpdatedAtLabel}
        noteError={noteError}
        noteSaving={noteSaving}
        handleNoteSave={handleNoteSave}
        withdrawDialogOpen={withdrawDialogOpen}
        closeWithdrawDialog={closeWithdrawDialog}
        withdrawTarget={withdrawTarget}
        withdrawDate={withdrawDate}
        setWithdrawDate={setWithdrawDate}
        withdrawPickerOpen={withdrawPickerOpen}
        setWithdrawPickerOpen={setWithdrawPickerOpen}
        withdrawError={withdrawError}
        withdrawSaving={withdrawSaving}
        handleWithdrawSave={handleWithdrawSave}
        transferDialogOpen={transferDialogOpen}
        closeTransferDialog={closeTransferDialog}
        transferTarget={transferTarget}
        transferDate={transferDate}
        setTransferDate={setTransferDate}
        transferPickerOpen={transferPickerOpen}
        setTransferPickerOpen={setTransferPickerOpen}
        transferCourseValue={transferCourseValue}
        setTransferCourseValue={setTransferCourseValue}
        transferWeeks={transferWeeks}
        transferError={transferError}
        transferSaving={transferSaving}
        transferCourseGroups={transferCourseGroups}
        transferCourseDays={transferCourseDays}
        transferExpectedEndDate={transferExpectedEndDate}
        handleTransferSave={handleTransferSave}
        mergeError={mergeError}
        setMergeError={setMergeError}
      />
    </>
  )
}
