import type { AuthUser } from "@/auth-routing"
import { PERMISSION_KEYS, hasPermission } from "@/permissions"

import { useRegistrations } from "./useRegistrations"
import { useRegistrationsTabActions } from "./useRegistrationsTabActions"
import { useRegistrationsTabDerived } from "./useRegistrationsTabDerived"
import { useRegistrationsViewState } from "./useRegistrationsViewState"

export function useRegistrationsTabShellProps(user: AuthUser | null) {
  const canAccessRegistrations = hasPermission(user, PERMISSION_KEYS.tabs.registrations)
  const canManageMerges =
    canAccessRegistrations && hasPermission(user, PERMISSION_KEYS.buttons.mergeManager)
  const canViewInstallments =
    canAccessRegistrations && hasPermission(user, PERMISSION_KEYS.buttons.installments)
  const canManageTransfers =
    canAccessRegistrations && hasPermission(user, PERMISSION_KEYS.buttons.transfers)

  const {
    courseConfigSetLoading,
    courseConfigSetError,
    courseConfigSets,
    selectedCourseConfigSet,
    selectCourseConfigSet,
    courseConfigSetCategories,
    courseConfigSetCourseSet,
    courseConfigSetBaseCourses,
    courseConfigSetIdToLabel,
    courseVariantRequiredSet,
    courseOptions,
    loading,
    error,
    setError,
    mergeError,
    setMergeError,
    registrations,
    filteredRegistrations,
    baseRegistrations,
    variantTabs,
    variantFilter,
    setVariantFilter,
    loadRegistrations,
    extensions,
    extensionsLoading,
    extensionsError,
    loadExtensions,
    merges,
    mergeManagerOpen,
    setMergeManagerOpen,
    mergeName,
    setMergeName,
    mergeCourses,
    setMergeCourses,
    mergeWeekMode,
    setMergeWeekMode,
    mergeWeekRangeInputs,
    setMergeWeekRangeInputs,
    addMerge,
    deleteMerge,
    toggleMergeActive,
    editingMergeId,
    startEditMerge,
    cancelEditMerge,
    activeMergesToday,
    mergedCourseSetToday,
    simulationDate,
    setSimulationDate,
    categoryFilter,
    changeCategoryFilter,
    courseFilter,
    setCourseFilter,
    search,
    setSearch,
  } = useRegistrations({
    loadMerges: canAccessRegistrations,
    loadExtensions: canViewInstallments,
    enableVariants: false,
  })

  const {
    selectedCourseConfigSetObj,
    showTransferChain,
    setShowTransferChain,
    mergeCourseOptions,
    mergeCourseTabs,
    resolveCourseDays,
    registrationMap,
    cardFilteredRegistrations,
    ganttGroups,
  } = useRegistrationsTabDerived({
    courseConfigSets,
    selectedCourseConfigSet,
    courseConfigSetBaseCourses,
    mergeCourses,
    courseFilter,
    merges,
    activeMergesToday,
    courseConfigSetIdToLabel,
    courseVariantRequiredSet,
    simulationDate,
    registrations,
    filteredRegistrations,
    baseRegistrations,
  })

  const { note, transfer, withdraw, handleCreateExtension } = useRegistrationsTabActions({
    courseOptions,
    registrations,
    selectedCourseConfigSetObj,
    selectedCourseConfigSet,
    loadRegistrations,
    loadExtensions,
    baseRegistrations,
    setError,
    resolveCourseDays,
  })

  const {
    activeGanttTab,
    setActiveGanttTab,
    activeGanttGroup,
    installmentMode,
    setInstallmentMode,
    chartOverlayOpen,
    setChartOverlayOpen,
    handleCourseFilterFromCard,
    handleCourseFilterFromSidebar,
    isAllView,
    showGantt,
    viewSource,
  } = useRegistrationsViewState({
    courseFilter,
    setCourseFilter,
    ganttGroups,
    canManageMerges,
    mergeManagerOpen,
    setMergeManagerOpen,
    canViewInstallments,
  })

  return {
    selectedCourseConfigSet,
    baseRegistrations,
    courseFilter,
    handleCourseFilterFromSidebar,
    courseConfigSetIdToLabel,
    courseVariantRequiredSet,
    merges: merges || [],
    activeMergesToday,
    mergedCourseSetToday,
    variantTabs,
    variantFilter,
    setVariantFilter,
    simulationDate,
    setSimulationDate,
    courseConfigSetLoading,
    courseConfigSets,
    selectCourseConfigSet,
    courseConfigSetCategories,
    categoryFilter,
    changeCategoryFilter,
    search,
    setSearch,
    loading,
    loadRegistrations,
    mergeManagerOpen,
    canManageMerges,
    setMergeManagerOpen,
    installmentMode,
    canViewInstallments,
    setInstallmentMode,
    courseConfigSetError,
    error,
    extensionsError,
    mergeCourseOptions,
    mergeCourseTabs,
    mergeName,
    setMergeName,
    mergeCourses,
    setMergeCourses,
    mergeWeekMode,
    setMergeWeekMode,
    mergeWeekRangeInputs,
    setMergeWeekRangeInputs,
    addMerge,
    deleteMerge,
    toggleMergeActive,
    editingMergeId,
    startEditMerge,
    cancelEditMerge,
    courseConfigSetCourseSet,
    filteredRegistrations,
    extensions,
    extensionsLoading,
    selectedCourseConfigSetObj,
    resolveCourseDays,
    handleCreateExtension,
    showGantt,
    showTransferChain,
    setShowTransferChain,
    ganttGroups,
    activeGanttTab,
    setActiveGanttTab,
    setChartOverlayOpen,
    registrationMap,
    openWithdrawDialog: withdraw.openWithdrawDialog,
    handleRestore: withdraw.handleRestore,
    canManageTransfers,
    openTransferDialog: transfer.openTransferDialog,
    handleTransferCancel: transfer.handleTransferCancel,
    openNoteDialog: note.openNoteDialog,
    isAllView,
    viewSource,
    handleCourseFilterFromCard,
    cardFilteredRegistrations,
    chartOverlayOpen,
    activeGanttGroup,
    noteDialogOpen: note.noteDialogOpen,
    closeNoteDialog: note.closeNoteDialog,
    noteTarget: note.noteTarget,
    noteValue: note.noteValue,
    setNoteValue: note.setNoteValue,
    noteUpdatedAtLabel: note.noteUpdatedAtLabel,
    noteError: note.noteError,
    noteSaving: note.noteSaving,
    handleNoteSave: note.handleNoteSave,
    withdrawDialogOpen: withdraw.withdrawDialogOpen,
    closeWithdrawDialog: withdraw.closeWithdrawDialog,
    withdrawTarget: withdraw.withdrawTarget,
    withdrawDate: withdraw.withdrawDate,
    setWithdrawDate: withdraw.setWithdrawDate,
    withdrawPickerOpen: withdraw.withdrawPickerOpen,
    setWithdrawPickerOpen: withdraw.setWithdrawPickerOpen,
    withdrawError: withdraw.withdrawError,
    withdrawSaving: withdraw.withdrawSaving,
    handleWithdrawSave: withdraw.handleWithdrawSave,
    transferDialogOpen: transfer.transferDialogOpen,
    closeTransferDialog: transfer.closeTransferDialog,
    transferTarget: transfer.transferTarget,
    transferDate: transfer.transferDate,
    setTransferDate: transfer.setTransferDate,
    transferPickerOpen: transfer.transferPickerOpen,
    setTransferPickerOpen: transfer.setTransferPickerOpen,
    transferCourseValue: transfer.transferCourseValue,
    setTransferCourseValue: transfer.setTransferCourseValue,
    transferWeeks: transfer.transferWeeks,
    transferError: transfer.transferError,
    transferSaving: transfer.transferSaving,
    transferCourseGroups: transfer.transferCourseGroups,
    transferCourseDays: transfer.transferCourseDays,
    transferExpectedEndDate: transfer.transferExpectedEndDate,
    handleTransferSave: transfer.handleTransferSave,
    mergeError,
    setMergeError,
  }
}
